#!/bin/bash

# Submit job to intel devcloud and print the output once finished
# Usage: ./submit <job_script.sh>

script=$1
#TODO: specify flags for qsub from args
qsub_id=$(qsub -l nodes=1:gpu:ppn=2 -d . $script)

job_id=$(echo "$qsub_id" | cut -d '.' -f 1)

echo "Job submitted"
echo ""
qstat 

echo -ne "\nWaiting for output file "
until [ -f $script.o$job_id ]; do
    sleep 1
    echo -n "."
done

cat $script.o$job_id
cat $script.e$job_id